injectEnvironmentFiles:
  - .env.local?

nodeLinker: node-modules

npmScopes:
  alliedtelesis-labs-nz:
    npmAlwaysAuth: true
    npmAuthToken: "${NPM_AUTH_TOKEN}"
    npmRegistryServer: "https://npm.pkg.github.com"