/**
 * Style Dictionary Build Service — server-side only.
 * Accepts raw token JSON and returns formatted output strings for all 6 formats.
 * Does NOT write to disk — all output captured in-memory via formatPlatform().
 */

import StyleDictionary from 'style-dictionary';
import type { BuildTokensRequest, BuildTokensResult, FormatOutput, BrandFormatOutput, ReferenceWarning } from '@/types';
import { stripPatternTokensForStyleDictionary } from '@/lib/stripPatternTokensForStyleDictionary';

const FORMATS = ['css', 'scss', 'less', 'js', 'ts', 'json', 'tailwind-v3', 'tailwind-v4', 'ios', 'android'] as const;
type Format = typeof FORMATS[number];

/**
 * Detect brand groups from token structure.
 *
 * Structure A (flat): { colors: {...}, spacing: {...} }
 *   → single brand "globals": tokens = the whole object
 *
 * Structure B (file-path keyed): { "globals/color-base.json": {...}, "brands/brand1.json": {...} }
 *   → group by first path segment.
 */
function detectBrands(tokens: Record<string, unknown>): { brand: string; tokens: Record<string, unknown> }[] {
  const keys = Object.keys(tokens);
  const isFilePath = keys.some(k => k.includes('/'));

  if (isFilePath) {
    // File-path keyed: group by first segment
    const brandMap = new Map<string, Record<string, unknown>>();
    for (const [filePath, data] of Object.entries(tokens)) {
      const brand = filePath.split('/')[0];
      if (!brandMap.has(brand)) brandMap.set(brand, {});
      const existing = brandMap.get(brand)!;
      if (data && typeof data === 'object' && !Array.isArray(data)) {
        Object.assign(existing, data as Record<string, unknown>);
      }
    }
    return Array.from(brandMap.entries()).map(([brand, t]) => ({ brand, tokens: t }));
  }

  // Flat structure: single brand
  return [{ brand: 'globals', tokens }];
}

/**
 * Deep-merge source into target (non-destructive: target keys win on conflict).
 * Used to merge globals tokens into each brand's token object.
 */
function deepMerge(
  target: Record<string, unknown>,
  source: Record<string, unknown>
): Record<string, unknown> {
  const result: Record<string, unknown> = { ...source };
  for (const [key, targetVal] of Object.entries(target)) {
    if (
      key in result &&
      targetVal &&
      typeof targetVal === 'object' &&
      !Array.isArray(targetVal) &&
      result[key] &&
      typeof result[key] === 'object' &&
      !Array.isArray(result[key])
    ) {
      result[key] = deepMerge(
        targetVal as Record<string, unknown>,
        result[key] as Record<string, unknown>
      );
    } else {
      result[key] = targetVal;
    }
  }
  return result;
}

/**
 * Merge the "globals" brand token object into every non-globals brand.
 * This makes each brand file self-contained (includes shared palette/global tokens).
 * The "globals" brand entry is removed from the output — it is only used as a merge source.
 *
 * If there is only one brand (and it is "globals"), return it as-is (single-brand collection).
 */
function mergeGlobalsIntoBrands(
  brands: { brand: string; tokens: Record<string, unknown> }[]
): { brand: string; tokens: Record<string, unknown> }[] {
  const globalsEntry = brands.find(b => b.brand === 'globals');
  const nonGlobalsBrands = brands.filter(b => b.brand !== 'globals');

  // Single-brand or no globals to merge
  if (!globalsEntry || nonGlobalsBrands.length === 0) {
    return brands;
  }

  // Merge globals into every non-globals brand (brand-specific tokens win on key conflict)
  return nonGlobalsBrands.map(({ brand, tokens: brandTokens }) => ({
    brand,
    tokens: deepMerge(brandTokens, globalsEntry.tokens),
  }));
}

/**
 * Normalize token keys: style-dictionary v5 uses $value/$type (W3C DTCG spec).
 * Our stored tokens may use `value`/`type` — convert before passing to SD.
 */
const AUTO_DESCRIPTION_RE = /^Generated by .+ node/;

function normalizeTokens(obj: Record<string, unknown>): Record<string, unknown> {
  const result: Record<string, unknown> = {};
  for (const [key, val] of Object.entries(obj)) {
    if (key === 'value' || key === '$value') {
      // Strip .value suffix from SD reference strings (e.g. {token.color.base.blue.200.value} → {token.color.base.blue.200})
      const normalized = (typeof val === 'string' && val.startsWith('{') && val.endsWith('}'))
        ? val.replace(/\.value\}$/, '}')
        : val;
      result['$value'] = normalized;
    } else if (key === 'type') {
      result['$type'] = val;
    } else if ((key === '$description' || key === 'description') && typeof val === 'string' && AUTO_DESCRIPTION_RE.test(val)) {
      // Drop auto-generated descriptions — they produce noise as CSS comments
    } else if (val && typeof val === 'object' && !Array.isArray(val)) {
      result[key] = normalizeTokens(val as Record<string, unknown>);
    } else {
      result[key] = val;
    }
  }
  return result;
}

/**
 * JS/TS reserved keywords that may appear as token group names.
 * When style-dictionary emits javascript/es6 output it produces:
 *   export const default = "..."   ← syntax error
 * We rename matching keys to append an underscore suffix: default → default_
 *
 * Only token group name keys are renamed (not SD meta-keys like $value, $type).
 */
const JS_RESERVED_KEYWORDS = new Set([
  'break', 'case', 'catch', 'class', 'const', 'continue', 'debugger',
  'default', 'delete', 'do', 'else', 'export', 'extends', 'finally',
  'for', 'function', 'if', 'import', 'in', 'instanceof', 'let', 'new',
  'null', 'return', 'static', 'super', 'switch', 'this', 'throw', 'true',
  'false', 'try', 'type', 'typeof', 'undefined', 'var', 'void', 'while',
  'with', 'yield', 'enum', 'interface', 'implements', 'package', 'private',
  'protected', 'public', 'abstract', 'as', 'async', 'await', 'from', 'of',
]);

/**
 * Recursively walk the token tree and rename any token-group key that is a
 * JS reserved keyword by appending an underscore suffix (e.g. default → default_).
 * SD meta-keys ($value, $type, $description) are never renamed.
 */
function sanitizeTokenKeys(obj: Record<string, unknown>): Record<string, unknown> {
  const result: Record<string, unknown> = {};
  for (const [key, val] of Object.entries(obj)) {
    // Never rename SD meta-keys
    const isMetaKey = key.startsWith('$');
    const safeKey = !isMetaKey && JS_RESERVED_KEYWORDS.has(key) ? `${key}_` : key;

    if (val && typeof val === 'object' && !Array.isArray(val)) {
      result[safeKey] = sanitizeTokenKeys(val as Record<string, unknown>);
    } else {
      result[safeKey] = val;
    }
  }
  return result;
}

// ─── Reference warning helpers ────────────────────────────────────────────────

/**
 * Walk a normalized token tree and collect every {ref} value with the declaring
 * path segments (used to build the CSS var name for the warning table).
 */
function scanRefs(
  obj: Record<string, unknown>,
  path: string[] = []
): Array<{ declPath: string[]; ref: string }> {
  const found: Array<{ declPath: string[]; ref: string }> = [];
  for (const [key, val] of Object.entries(obj)) {
    if (key === '$value') {
      if (typeof val === 'string' && val.startsWith('{') && val.endsWith('}')) {
        found.push({ declPath: path, ref: val });
      }
    } else if (val && typeof val === 'object' && !Array.isArray(val) && !key.startsWith('$')) {
      found.push(...scanRefs(val as Record<string, unknown>, [...path, key]));
    }
  }
  return found;
}

/** Check whether a dot-path (e.g. "token.text.base") resolves to a token node */
function pathExistsInTree(tree: Record<string, unknown>, dotPath: string): boolean {
  const parts = dotPath.split('.');
  let node: unknown = tree;
  for (const part of parts) {
    if (!node || typeof node !== 'object' || !(part in (node as Record<string, unknown>))) return false;
    node = (node as Record<string, unknown>)[part];
  }
  if (!node || typeof node !== 'object') return false;
  const n = node as Record<string, unknown>;
  return '$value' in n || 'value' in n;
}

/** Convert path segments to a CSS custom property name, applying kebab-case */
function pathToCssVar(segments: string[]): string {
  return '--' + segments
    .map(s => s.replace(/([A-Z])/g, c => `-${c.toLowerCase()}`))
    .join('-');
}

/**
 * Compare the normalized token tree against itself and return warnings for every
 * reference whose target token does not exist in the same tree.
 */
function detectBrokenRefs(normalizedTree: Record<string, unknown>): ReferenceWarning[] {
  const refs = scanRefs(normalizedTree);
  return refs
    .filter(({ ref }) => {
      const dotPath = ref.slice(1, -1).replace(/\.value$/, '');
      return !pathExistsInTree(normalizedTree, dotPath);
    })
    .map(({ declPath, ref }) => {
      const dotPath = ref.slice(1, -1).replace(/\.value$/, '');
      return {
        tokenVar: pathToCssVar(declPath),
        reference: ref,
        referencedVar: pathToCssVar(dotPath.split('.')),
        issue: 'broken' as const,
      };
    });
}

// ─── Tailwind config generator ────────────────────────────────────────────────

/** Maps DTCG / common token $type values to Tailwind v3 theme.extend categories */
const TYPE_TO_TAILWIND_V3_CATEGORY: Record<string, string> = {
  color:          'colors',
  dimension:      'spacing',
  fontSize:       'fontSize',
  fontWeight:     'fontWeight',
  fontFamily:     'fontFamily',
  lineHeight:     'lineHeight',
  letterSpacing:  'letterSpacing',
  borderRadius:   'borderRadius',
  borderWidth:    'borderWidth',
  opacity:        'opacity',
  shadow:         'boxShadow',
  duration:       'transitionDuration',
  cubicBezier:    'transitionTimingFunction',
};

/** Maps DTCG / common token $type values to Tailwind v4 @theme CSS variable prefixes */
const TYPE_TO_TAILWIND_V4_PREFIX: Record<string, string> = {
  color:          'color',
  dimension:      'spacing',
  fontSize:       'text',
  fontWeight:     'font-weight',
  fontFamily:     'font',
  lineHeight:     'leading',
  letterSpacing:  'tracking',
  borderRadius:   'radius',
  borderWidth:    'border-width',
  opacity:        'opacity',
  shadow:         'shadow',
  duration:       'duration',
  cubicBezier:    'ease',
};

interface TailwindTokenEntry {
  cssVar: string;    // e.g. '--token-color-primary-500'
  keyParts: string[]; // path segments after namespace, kebab-cased: ['color', 'primary', '500']
  type: string;      // DTCG $type value
}

/**
 * Walk the normalized token tree and collect typed token entries.
 * Inherits $type from ancestor nodes (style-dictionary convention).
 * Strips the namespace root (first path segment) from keyParts.
 */
function walkForTailwind(
  obj: Record<string, unknown>,
  path: string[],
  inheritedType: string | undefined,
  out: TailwindTokenEntry[]
): void {
  const nodeType = (typeof obj['$type'] === 'string' ? obj['$type'] : null) ?? inheritedType;

  if ('$value' in obj) {
    if (nodeType) {
      const keyParts = path.slice(1).map(s => s.replace(/([A-Z])/g, c => `-${c.toLowerCase()}`));
      out.push({ cssVar: pathToCssVar(path), keyParts, type: nodeType });
    }
    return;
  }

  for (const [k, v] of Object.entries(obj)) {
    if (k.startsWith('$')) continue;
    if (v && typeof v === 'object' && !Array.isArray(v)) {
      walkForTailwind(v as Record<string, unknown>, [...path, k], nodeType, out);
    }
  }
}

/**
 * Generate a tailwind.config.js (v3) that maps every typed token to a CSS
 * variable reference inside theme.extend.
 */
function generateTailwindV3Config(normalizedTokens: Record<string, unknown>): string {
  const entries: TailwindTokenEntry[] = [];
  walkForTailwind(normalizedTokens, [], undefined, entries);

  const categoryMap = new Map<string, Array<{ key: string; cssVar: string }>>();
  for (const { cssVar, keyParts, type } of entries) {
    const category = TYPE_TO_TAILWIND_V3_CATEGORY[type];
    if (!category) continue;
    const key = keyParts.join('-');
    if (!categoryMap.has(category)) categoryMap.set(category, []);
    categoryMap.get(category)!.push({ key, cssVar });
  }

  if (categoryMap.size === 0) {
    return `/** @type {import('tailwindcss').Config} */\nmodule.exports = {\n  theme: {\n    extend: {},\n  },\n};\n`;
  }

  const categoryEntries = Array.from(categoryMap.entries())
    .map(([category, tokens]) => {
      const tokenLines = tokens
        .map(({ key, cssVar }) => `      '${key}': 'var(${cssVar})'`)
        .join(',\n');
      return `    ${category}: {\n${tokenLines},\n    }`;
    })
    .join(',\n');

  return `/** @type {import('tailwindcss').Config} */\nmodule.exports = {\n  theme: {\n    extend: {\n${categoryEntries},\n    },\n  },\n};\n`;
}

/**
 * Generate a Tailwind v4 CSS file using the @theme directive.
 * Each token becomes a --{prefix}-{name} variable that references the token CSS var.
 * The first keyPart is stripped when it matches the type name (avoids --color-color-...).
 */
function generateTailwindV4Config(normalizedTokens: Record<string, unknown>): string {
  const entries: TailwindTokenEntry[] = [];
  walkForTailwind(normalizedTokens, [], undefined, entries);

  const lines: string[] = [];
  for (const { cssVar, keyParts, type } of entries) {
    const prefix = TYPE_TO_TAILWIND_V4_PREFIX[type];
    if (!prefix) continue;
    // Strip leading keyPart if it matches the type name (e.g. 'color' for type 'color')
    const stripped = keyParts[0] === type.toLowerCase() ? keyParts.slice(1) : keyParts;
    const name = stripped.join('-');
    if (!name) continue;
    lines.push(`  --${prefix}-${name}: var(${cssVar});`);
  }

  if (lines.length === 0) {
    return `@import "tailwindcss";\n\n@theme {\n}\n`;
  }

  return `@import "tailwindcss";\n\n@theme {\n${lines.join('\n')}\n}\n`;
}

// ─── Brand token builder ───────────────────────────────────────────────────────

/**
 * Build a single brand's tokens into all 7 formats using style-dictionary v5 programmatic API.
 * Returns a map from format name to file content string, plus any broken-ref warnings.
 */
async function buildBrandTokens(
  brandTokens: Record<string, unknown>,
  namespace: string,
  brand: string
): Promise<{ results: Map<Format, string>; warnings: ReferenceWarning[] }> {
  const results = new Map<Format, string>();

  const normalizedBrandTokens = normalizeTokens(brandTokens);

  // Detect broken references before SD processes the tree (SD may silently drop them)
  const warnings = detectBrokenRefs(normalizedBrandTokens);

  // Sanitize reserved JS keywords in token group names before passing to SD.
  // Tokens from MongoDB are already wrapped with a namespace key (e.g. { token: { ... } })
  // so we pass them directly — no additional wrapping to avoid --token-token-... double prefix.
  const sanitizedTokens = sanitizeTokenKeys(normalizedBrandTokens);

  // Generate Tailwind configs directly (do not go through Style Dictionary)
  results.set('tailwind-v3', generateTailwindV3Config(normalizedBrandTokens));
  results.set('tailwind-v4', generateTailwindV4Config(normalizedBrandTokens));

  type SdFormat = Exclude<Format, 'tailwind-v3' | 'tailwind-v4'>;
  const formatConfigs: Record<SdFormat, { formatter: string; extension: string; transformGroup: string; outputReferences: boolean }> = {
    css:     { formatter: 'css/variables',                transformGroup: 'css',      extension: 'css',   outputReferences: true  },
    scss:    { formatter: 'scss/variables',               transformGroup: 'css',      extension: 'scss',  outputReferences: true  },
    less:    { formatter: 'less/variables',               transformGroup: 'css',      extension: 'less',  outputReferences: true  },
    js:      { formatter: 'javascript/es6',               transformGroup: 'js',       extension: 'js',    outputReferences: false },
    ts:      { formatter: 'typescript/es6-declarations',  transformGroup: 'js',       extension: 'd.ts',  outputReferences: false },
    json:    { formatter: 'json/nested',                  transformGroup: 'js',       extension: 'json',  outputReferences: false },
    ios:     { formatter: 'ios-swift/class.swift',        transformGroup: 'ios-swift', extension: 'swift', outputReferences: false },
    android: { formatter: 'android/resources',            transformGroup: 'android',  extension: 'xml',   outputReferences: false },
  };

  for (const [fmt, { formatter, extension, transformGroup, outputReferences }] of Object.entries(formatConfigs) as [SdFormat, { formatter: string; extension: string; transformGroup: string; outputReferences: boolean }][]) {
    try {
      const sd = new StyleDictionary({
        tokens: sanitizedTokens as Record<string, never>,
        platforms: {
          [fmt]: {
            transformGroup,
            // No prefix: the token tree already contains the namespace as its root key
            // (e.g. { token: { common: { ... } } }) so SD derives --token-common-...
            // directly from the path. Adding prefix here would produce --token-token-...
            files: [
              {
                destination: `tokens-${brand}.${extension}`,
                format: formatter,
                options: {
                  // CSS/SCSS/LESS: emit var(--token-x) for reference tokens instead of resolved values.
                  // JS/TS/JSON: keep resolved values (var() is not valid in JS contexts).
                  outputReferences,
                },
              },
            ],
          },
        },
        // Treat broken token references as console output, not thrown errors.
        // Tokens stored in MongoDB may contain reference values (e.g. {colors.primary})
        // that point outside the current brand's token set after globals merging.
        log: {
          verbosity: 'silent',
          warnings: 'disabled',
          errors: { brokenReferences: 'console' },
        },
      });

      // SD v5: must call init() before formatPlatform()
      await sd.init();

      // formatPlatform returns array of { output: string, destination: string }
      const platformFiles = await sd.formatPlatform(fmt);
      let capturedContent = '';
      if (Array.isArray(platformFiles) && platformFiles.length > 0) {
        capturedContent = (platformFiles[0] as { output: string; destination: string }).output ?? '';
      }

      results.set(fmt, capturedContent);
    } catch (err) {
      // Format failed — store empty string with error comment
      results.set(fmt, `/* Build error for ${fmt}: ${err instanceof Error ? err.message : String(err)} */`);
    }
  }

  return { results, warnings };
}

/**
 * Build combined light+dark output for CSS, SCSS, LESS, JS, and TS formats.
 *
 * CSS/SCSS/LESS strategy: run SD for each token set separately, then post-process:
 *   - Light output: unchanged (:root { ... })
 *   - Dark output: replace ':root {' with '[data-color-mode="dark"] {'
 *   - Combined: lightContent + '\n\n' + darkContent
 *
 * JS/TS strategy: run SD for dark tokens with '${namespace}Dark' namespace prefix,
 * producing differently-named exports (e.g. TokenDarkColorPrimary), then concatenate.
 *
 * JSON format: not combined — dark tokens are omitted from JSON (JSON format excluded
 * per existing COMMENT_FORMATS pattern; no comments, no dark block needed).
 *
 * Safety: if ':root {' is not found in dark SD output, log a warning and wrap manually.
 */
async function buildCombinedOutput(
  lightTokens: Record<string, unknown>,
  darkTokens: Record<string, unknown>,
  namespace: string,
  brand: string
): Promise<{ results: Map<Format, string>; warnings: ReferenceWarning[] }> {
  const results = new Map<Format, string>();

  // Build both token sets
  const { results: lightMap, warnings: lightWarnings } = await buildBrandTokens(lightTokens, namespace, brand);
  const { results: darkMap,  warnings: darkWarnings  } = await buildBrandTokens(darkTokens, `${namespace}Dark`, `${brand}-dark`);
  const warnings = [...lightWarnings, ...darkWarnings];

  const CSS_FORMATS: Format[] = ['css', 'scss', 'less'];
  const JS_FORMATS:  Format[] = ['js', 'ts'];

  // CSS/SCSS/LESS: replace :root { with [data-color-mode="dark"] { in dark output
  for (const fmt of CSS_FORMATS) {
    const lightContent = lightMap.get(fmt) ?? '';
    const rawDark = darkMap.get(fmt) ?? '';

    const darkSelector = '[data-color-mode="dark"]';
    let darkContent: string;

    if (rawDark.includes(':root {')) {
      darkContent = rawDark.replace(':root {', `${darkSelector} {`);
    } else {
      // Safety fallback: SD output changed format — wrap manually
      console.warn(`[buildCombinedOutput] Expected ':root {' in ${fmt} dark output but not found. Wrapping manually.`);
      darkContent = `${darkSelector} {\n${rawDark}\n}`;
    }

    results.set(fmt, `${lightContent}\n\n${darkContent}`);
  }

  // JS/TS: namespace prefix approach — light uses 'namespace', dark uses 'namespaceDark'
  // Results in: TokenColorPrimary = "..." (light) + TokenDarkColorPrimary = "..." (dark)
  for (const fmt of JS_FORMATS) {
    const lightContent = lightMap.get(fmt) ?? '';
    const darkContent  = darkMap.get(fmt) ?? '';
    results.set(fmt, `${lightContent}\n\n/* Dark mode tokens */\n${darkContent}`);
  }

  // JSON: pass through light only (JSON spec forbids comments; no dark block structure)
  results.set('json', lightMap.get('json') ?? '');

  // Tailwind: pass through light only (dark tokens map to the same CSS vars; no duplication needed)
  results.set('tailwind-v3', lightMap.get('tailwind-v3') ?? '');
  results.set('tailwind-v4', lightMap.get('tailwind-v4') ?? '');

  // Mobile: pass through light only (dark mode handled natively on each platform)
  results.set('ios', lightMap.get('ios') ?? '');
  results.set('android', lightMap.get('android') ?? '');

  return { results, warnings };
}

/**
 * Main export: build all formats for all brands from raw token JSON.
 *
 * GLOBALS MERGING: globals tokens are merged into every non-globals brand so each
 * output file is self-contained (user decision — locked). The "globals" brand is NOT
 * emitted as a separate output file when non-globals brands exist.
 */
export async function buildTokens(request: BuildTokensRequest): Promise<BuildTokensResult> {
  const { namespace, collectionName, colorMode } = request;

  const tokens = stripPatternTokensForStyleDictionary(
    request.tokens as Record<string, unknown>
  );
  const darkTokens = request.darkTokens
    ? stripPatternTokensForStyleDictionary(request.darkTokens as Record<string, unknown>)
    : undefined;

  const rawBrands = detectBrands(tokens);

  // Merge globals into each non-globals brand (user decision: each brand file is self-contained)
  const brands = mergeGlobalsIntoBrands(rawBrands);

  const formatOutputs = new Map<Format, FormatOutput>();
  const allWarnings: ReferenceWarning[] = [];

  // Initialize format outputs
  for (const fmt of FORMATS) {
    formatOutputs.set(fmt, { format: fmt, outputs: [] });
  }

  // Build each brand
  for (const { brand, tokens: brandTokens } of brands) {
    let builtFormats: Map<Format, string>;
    let brandWarnings: ReferenceWarning[];

    if (darkTokens) {
      // Combined light+dark output: detect dark brands the same way
      const rawDarkBrands = detectBrands(darkTokens);
      const darkBrands = mergeGlobalsIntoBrands(rawDarkBrands);
      // Match by brand name; fall back to first dark brand if no name match
      const darkBrand = darkBrands.find(b => b.brand === brand) ?? darkBrands[0];
      if (darkBrand) {
        const built = await buildCombinedOutput(brandTokens, darkBrand.tokens, namespace, brand);
        builtFormats = built.results;
        brandWarnings = built.warnings;
      } else {
        const built = await buildBrandTokens(brandTokens, namespace, brand);
        builtFormats = built.results;
        brandWarnings = built.warnings;
      }
    } else {
      const built = await buildBrandTokens(brandTokens, namespace, brand);
      builtFormats = built.results;
      brandWarnings = built.warnings;
    }

    allWarnings.push(...brandWarnings);

    // When a dark-mode theme is exported directly, replace :root { with the dark selector
    if (colorMode === 'dark' && !darkTokens) {
      const darkSelector = '[data-color-mode="dark"]';
      for (const fmt of (['css', 'scss', 'less'] as Format[])) {
        const content = builtFormats.get(fmt) ?? '';
        if (content.includes(':root {')) {
          builtFormats.set(fmt, content.replace(':root {', `${darkSelector} {`));
        }
      }
    }

    for (const fmt of FORMATS) {
      const content = builtFormats.get(fmt) ?? '';
      let filename: string;
      if (fmt === 'tailwind-v3') {
        filename = brands.length > 1 ? `tailwind.config.${brand}.js` : 'tailwind.config.js';
      } else if (fmt === 'tailwind-v4') {
        filename = brands.length > 1 ? `tailwind.${brand}.css` : 'tailwind.css';
      } else if (fmt === 'ios') {
        filename = `tokens-${brand}.swift`;
      } else if (fmt === 'android') {
        filename = `tokens-${brand}.xml`;
      } else {
        const ext = fmt === 'ts' ? 'd.ts' : fmt;
        filename = `tokens-${brand}.${ext}`;
      }
      formatOutputs.get(fmt)!.outputs.push({ brand, content, filename } as BrandFormatOutput);
    }
  }

  return {
    formats: Array.from(formatOutputs.values()),
    collectionName,
    ...(allWarnings.length > 0 && { warnings: allWarnings }),
  };
}
