/* eslint-disable */
/* tslint:disable */
/**
 * This is an autogenerated file created by the Stencil compiler.
 * It contains typing information for all components that exist in this project.
 */
import { HTMLStencilElement, JSXBase } from "@stencil/core/internal";
export namespace Components {
    interface AppHome {
    }
    interface AppProfile {
        "name": string;
    }
    interface AppRoot {
    }
    interface GithubConfig {
        "cssClass": string;
    }
    interface GithubDirectoryPicker {
        "availableBranches": string[];
        "branch": string;
        "defaultFilename": string;
        "githubToken": string;
        "mode": 'export' | 'import';
        "repository": string;
    }
    interface TokenGenerator {
    }
    interface TokenManagerApp {
    }
}
export interface GithubConfigCustomEvent<T> extends CustomEvent<T> {
    detail: T;
    target: HTMLGithubConfigElement;
}
export interface GithubDirectoryPickerCustomEvent<T> extends CustomEvent<T> {
    detail: T;
    target: HTMLGithubDirectoryPickerElement;
}
declare global {
    interface HTMLAppHomeElement extends Components.AppHome, HTMLStencilElement {
    }
    var HTMLAppHomeElement: {
        prototype: HTMLAppHomeElement;
        new (): HTMLAppHomeElement;
    };
    interface HTMLAppProfileElement extends Components.AppProfile, HTMLStencilElement {
    }
    var HTMLAppProfileElement: {
        prototype: HTMLAppProfileElement;
        new (): HTMLAppProfileElement;
    };
    interface HTMLAppRootElement extends Components.AppRoot, HTMLStencilElement {
    }
    var HTMLAppRootElement: {
        prototype: HTMLAppRootElement;
        new (): HTMLAppRootElement;
    };
    interface HTMLGithubConfigElementEventMap {
        "configChange": GitHubRepo | null;
    }
    interface HTMLGithubConfigElement extends Components.GithubConfig, HTMLStencilElement {
        addEventListener<K extends keyof HTMLGithubConfigElementEventMap>(type: K, listener: (this: HTMLGithubConfigElement, ev: GithubConfigCustomEvent<HTMLGithubConfigElementEventMap[K]>) => any, options?: boolean | AddEventListenerOptions): void;
        addEventListener<K extends keyof DocumentEventMap>(type: K, listener: (this: Document, ev: DocumentEventMap[K]) => any, options?: boolean | AddEventListenerOptions): void;
        addEventListener<K extends keyof HTMLElementEventMap>(type: K, listener: (this: HTMLElement, ev: HTMLElementEventMap[K]) => any, options?: boolean | AddEventListenerOptions): void;
        addEventListener(type: string, listener: EventListenerOrEventListenerObject, options?: boolean | AddEventListenerOptions): void;
        removeEventListener<K extends keyof HTMLGithubConfigElementEventMap>(type: K, listener: (this: HTMLGithubConfigElement, ev: GithubConfigCustomEvent<HTMLGithubConfigElementEventMap[K]>) => any, options?: boolean | EventListenerOptions): void;
        removeEventListener<K extends keyof DocumentEventMap>(type: K, listener: (this: Document, ev: DocumentEventMap[K]) => any, options?: boolean | EventListenerOptions): void;
        removeEventListener<K extends keyof HTMLElementEventMap>(type: K, listener: (this: HTMLElement, ev: HTMLElementEventMap[K]) => any, options?: boolean | EventListenerOptions): void;
        removeEventListener(type: string, listener: EventListenerOrEventListenerObject, options?: boolean | EventListenerOptions): void;
    }
    var HTMLGithubConfigElement: {
        prototype: HTMLGithubConfigElement;
        new (): HTMLGithubConfigElement;
    };
    interface HTMLGithubDirectoryPickerElementEventMap {
        "selectPath": { path: string; branch: string };
        "cancel": void;
    }
    interface HTMLGithubDirectoryPickerElement extends Components.GithubDirectoryPicker, HTMLStencilElement {
        addEventListener<K extends keyof HTMLGithubDirectoryPickerElementEventMap>(type: K, listener: (this: HTMLGithubDirectoryPickerElement, ev: GithubDirectoryPickerCustomEvent<HTMLGithubDirectoryPickerElementEventMap[K]>) => any, options?: boolean | AddEventListenerOptions): void;
        addEventListener<K extends keyof DocumentEventMap>(type: K, listener: (this: Document, ev: DocumentEventMap[K]) => any, options?: boolean | AddEventListenerOptions): void;
        addEventListener<K extends keyof HTMLElementEventMap>(type: K, listener: (this: HTMLElement, ev: HTMLElementEventMap[K]) => any, options?: boolean | AddEventListenerOptions): void;
        addEventListener(type: string, listener: EventListenerOrEventListenerObject, options?: boolean | AddEventListenerOptions): void;
        removeEventListener<K extends keyof HTMLGithubDirectoryPickerElementEventMap>(type: K, listener: (this: HTMLGithubDirectoryPickerElement, ev: GithubDirectoryPickerCustomEvent<HTMLGithubDirectoryPickerElementEventMap[K]>) => any, options?: boolean | EventListenerOptions): void;
        removeEventListener<K extends keyof DocumentEventMap>(type: K, listener: (this: Document, ev: DocumentEventMap[K]) => any, options?: boolean | EventListenerOptions): void;
        removeEventListener<K extends keyof HTMLElementEventMap>(type: K, listener: (this: HTMLElement, ev: HTMLElementEventMap[K]) => any, options?: boolean | EventListenerOptions): void;
        removeEventListener(type: string, listener: EventListenerOrEventListenerObject, options?: boolean | EventListenerOptions): void;
    }
    var HTMLGithubDirectoryPickerElement: {
        prototype: HTMLGithubDirectoryPickerElement;
        new (): HTMLGithubDirectoryPickerElement;
    };
    interface HTMLTokenGeneratorElement extends Components.TokenGenerator, HTMLStencilElement {
    }
    var HTMLTokenGeneratorElement: {
        prototype: HTMLTokenGeneratorElement;
        new (): HTMLTokenGeneratorElement;
    };
    interface HTMLTokenManagerAppElement extends Components.TokenManagerApp, HTMLStencilElement {
    }
    var HTMLTokenManagerAppElement: {
        prototype: HTMLTokenManagerAppElement;
        new (): HTMLTokenManagerAppElement;
    };
    interface HTMLElementTagNameMap {
        "app-home": HTMLAppHomeElement;
        "app-profile": HTMLAppProfileElement;
        "app-root": HTMLAppRootElement;
        "github-config": HTMLGithubConfigElement;
        "github-directory-picker": HTMLGithubDirectoryPickerElement;
        "token-generator": HTMLTokenGeneratorElement;
        "token-manager-app": HTMLTokenManagerAppElement;
    }
}
declare namespace LocalJSX {
    interface AppHome {
    }
    interface AppProfile {
        "name"?: string;
    }
    interface AppRoot {
    }
    interface GithubConfig {
        "cssClass"?: string;
        "onConfigChange"?: (event: GithubConfigCustomEvent<GitHubRepo | null>) => void;
    }
    interface GithubDirectoryPicker {
        "availableBranches"?: string[];
        "branch"?: string;
        "defaultFilename"?: string;
        "githubToken"?: string;
        "mode"?: 'export' | 'import';
        "onCancel"?: (event: GithubDirectoryPickerCustomEvent<void>) => void;
        "onSelectPath"?: (event: GithubDirectoryPickerCustomEvent<{ path: string; branch: string }>) => void;
        "repository"?: string;
    }
    interface TokenGenerator {
    }
    interface TokenManagerApp {
    }
    interface IntrinsicElements {
        "app-home": AppHome;
        "app-profile": AppProfile;
        "app-root": AppRoot;
        "github-config": GithubConfig;
        "github-directory-picker": GithubDirectoryPicker;
        "token-generator": TokenGenerator;
        "token-manager-app": TokenManagerApp;
    }
}
export { LocalJSX as JSX };
declare module "@stencil/core" {
    export namespace JSX {
        interface IntrinsicElements {
            "app-home": LocalJSX.AppHome & JSXBase.HTMLAttributes<HTMLAppHomeElement>;
            "app-profile": LocalJSX.AppProfile & JSXBase.HTMLAttributes<HTMLAppProfileElement>;
            "app-root": LocalJSX.AppRoot & JSXBase.HTMLAttributes<HTMLAppRootElement>;
            "github-config": LocalJSX.GithubConfig & JSXBase.HTMLAttributes<HTMLGithubConfigElement>;
            "github-directory-picker": LocalJSX.GithubDirectoryPicker & JSXBase.HTMLAttributes<HTMLGithubDirectoryPickerElement>;
            "token-generator": LocalJSX.TokenGenerator & JSXBase.HTMLAttributes<HTMLTokenGeneratorElement>;
            "token-manager-app": LocalJSX.TokenManagerApp & JSXBase.HTMLAttributes<HTMLTokenManagerAppElement>;
        }
    }
}
